### ISSUE TITLE
Code for Maria Sequence

### ISSUE THREAD

**Issue by niujinshuchong** [facebookresearch/NSVF#7]
Hi, thanks for sharing this great work. 

The code for Maria Sequence is missing in the repo. Could you please release the code and the data for Maria Sequence.

Thank you very much.

**Comment by lingjie0206** [comment]
Hi, thank you for your interest! 
The implementation of this part is included in the code, please refer to the 'shared_nsvf' model in https://github.com/facebookresearch/NSVF/blob/master/fairnr/models/multi_nsvf.py
But unfortunately, due to the copyright of the Maria sequence, we're not allowed to make it public.
